---
- name: My Test Playbook
  hosts: all
  become: true
  tasks:
  - name: add multiple users
    user:
      name: "{{item}}"
      state: present 
    with_items:
        - Kamini
        - Rakshita
        - tameshwar
